[project]
name = "ohlcv"
version = "0.1.0"
description = ""
authors = [
    {name = "chuckha",email = "chuckha@hey.com"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "lightql @ file:///Users/cha/Development/github.com/chuckha/finance/lightql",
    "yfinance (>=0.2.65,<0.3.0)",
    "pandas-market-calendars (>=5.1.1,<6.0.0)",
    "scipy (>=1.16.1,<2.0.0)"
]
packages = [ { include = "ohlcv" } ]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
lightql = {develop = true}
